name = "v2raydata2025"
main = "src/worker.ts"
compatibility_date = "2025-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "95a4b31653104ef293bf9bd1c3bf5c66" }
]
